### ISSUE TITLE
Error occurred while using child template calling template that use pdf util

### ISSUE THREAD

**Issue by dfiorentin** [jsreport/jsreport-pdf-utils#7]
Im trying to use {child} function to call a template that use pdf util to add an header. If i do so i've got the standard error:
Error occured - Error during rendering report: Error during rendering report: undefined

I've replicated an example inside the playground, at https://playground.jsreport.net/studio/workspace/SyzMxq0ym/30
Just click on run on the "error_with_merge" template to show up the error.

Thank you for your support.

**Comment by bjrmatos** [comment]
in jsreport v2, this throws an error about `Invalid PDF structure`. there seems to be an issue when trying to run a template with pdf-utils as a child template, but anyway what you are trying to do won't work, calling a child template that outputs pdf inside another template that outputs html will only give you bad results because you are trying insert PDF (child template output) into html (original template)

**Comment by dfiorentin** [comment]
So how could I structure my reports?  I have to call the child template (a phantom-pdf) that is merged through pdf-util with another report (even this phantom-pdf).  It seems that no matter what is the father's recipe (I've tried with phantom-pdf, html,text), I always have Error: undefined because my childs are phantom. I cannot change my child's template because i have some external constraints. Any suggestion?

**Comment by pofider** [comment]
Solved directly with @dfiorentin .
